package com.multimedianetwork.gliding.model;

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import sun.misc.BASE64Encoder;

/**
 * MembershipRequest generated by hbm2java
 */
@Entity
@Table(name = "membership_request", catalog = "gliding"
)
public class MembershipRequest implements java.io.Serializable {

    private Integer id;
    private String lastName;
    private String firstName;
    private String citizenship;
    private String icSerie;
    private String icNumber;
    private String pasportNumber;
    private String cnp;
    private String addressCity;
    private String addressStreet;
    private String addressNumber;
    private String addressFlat;
    private String addressSc;
    private String addressFloor;
    private String addressApartment;
    private String addressCode;
    private String addressCounty;
    private String addressCountry;
    private String telephone;
    private String email;
    private Byte birthDateDay;
    private Byte birthDateMonth;
    private Short birthDateYear;
    private String birthPlaceCity;
    private String birthPlaceCounty;
    private String birthPlaceCountry;
    private boolean temporaryMembership;
    private String licenseNumber;
    private boolean BLicense;
    private boolean BTowingWinch;
    private boolean BTowingPlane;
    private boolean BTowingSelf;
    private boolean BAcrobaticFlight;
    private boolean BInCloudsFlight;
    private boolean BNightFlight;
    private boolean BControlFlight;
    private boolean BGliderLicense;
    private boolean BMotorgliderLicense;
    private boolean BInstructor;
    private boolean BTestPilot;
    private Integer experienceNrHours;
    private Integer experienceNrTakeoffs;
    private Integer experienceNrKm;
    private byte[] photo;
    private Member member;
    private Date addDate;

    public MembershipRequest() {
    }

    public MembershipRequest(String lastName, String firstName, String citizenship,
            String addressCity, String addressStreet, String addressCountry, String telephone, String email,
            byte birthDateDay, byte birthDateMonth, short birthDateYear,
            String birthPlaceCity, boolean temporaryMembership,
            boolean BLicense, boolean BTowingWinch, boolean BTowingPlane,
            boolean BTowingSelf, boolean BAcrobaticFlight, boolean BInCloudsFlight,
            boolean BNightFlight, boolean BControlFlight, boolean BGliderLicense,
            boolean BMotorgliderLicense, boolean BInstructor, boolean BTestPilot) {

        this.lastName = lastName;
        this.firstName = firstName;
        this.citizenship = citizenship;
        this.addressCity = addressCity;
        this.addressStreet = addressStreet;
        this.addressCountry = addressCountry;
        this.telephone = telephone;
        this.email = email;
        this.birthDateDay = birthDateDay;
        this.birthDateMonth = birthDateMonth;
        this.birthDateYear = birthDateYear;
        this.birthPlaceCity = birthPlaceCity;
        this.temporaryMembership = temporaryMembership;
        this.BLicense = BLicense;
        this.BTowingWinch = BTowingWinch;
        this.BTowingPlane = BTowingPlane;
        this.BTowingSelf = BTowingSelf;
        this.BAcrobaticFlight = BAcrobaticFlight;
        this.BInCloudsFlight = BInCloudsFlight;
        this.BNightFlight = BNightFlight;
        this.BControlFlight = BControlFlight;
        this.BGliderLicense = BGliderLicense;
        this.BMotorgliderLicense = BMotorgliderLicense;
        this.BInstructor = BInstructor;
        this.BTestPilot = BTestPilot;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)

    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "last_name", nullable = false, length = 20)
    public String getLastName() {
        return this.lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    @Column(name = "first_name", nullable = false, length = 30)
    public String getFirstName() {
        return this.firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    @Column(name = "citizenship", nullable = false, length = 20)
    public String getCitizenship() {
        return this.citizenship;
    }

    public void setCitizenship(String citizenship) {
        this.citizenship = citizenship;
    }

    @Column(name = "ic_serie", length = 3)
    public String getIcSerie() {
        return this.icSerie;
    }

    public void setIcSerie(String icSerie) {
        this.icSerie = icSerie;
    }

    @Column(name = "ic_number", length = 10)
    public String getIcNumber() {
        return this.icNumber;
    }

    public void setIcNumber(String icNumber) {
        this.icNumber = icNumber;
    }

    @Column(name = "pasport_number", length = 20)
    public String getPasportNumber() {
        return this.pasportNumber;
    }

    public void setPasportNumber(String pasportNumber) {
        this.pasportNumber = pasportNumber;
    }

    @Column(name = "cnp", length = 13)
    public String getCnp() {
        return this.cnp;
    }

    public void setCnp(String cnp) {
        this.cnp = cnp;
    }

    @Column(name = "address_city", nullable = false, length = 30)
    public String getAddressCity() {
        return this.addressCity;
    }

    public void setAddressCity(String addressCity) {
        this.addressCity = addressCity;
    }

    @Column(name = "address_street", nullable = false, length = 30)
    public String getAddressStreet() {
        return this.addressStreet;
    }

    public void setAddressStreet(String addressStreet) {
        this.addressStreet = addressStreet;
    }

    @Column(name = "address_number", length = 5)
    public String getAddressNumber() {
        return this.addressNumber;
    }

    public void setAddressNumber(String addressNumber) {
        this.addressNumber = addressNumber;
    }

    @Column(name = "address_flat", length = 10)
    public String getAddressFlat() {
        return this.addressFlat;
    }

    public void setAddressFlat(String addressFlat) {
        this.addressFlat = addressFlat;
    }

    @Column(name = "address_floor", length = 3)
    public String getAddressFloor() {
        return this.addressFloor;
    }

    public void setAddressFloor(String addressFloor) {
        this.addressFloor = addressFloor;
    }

    @Column(name = "address_code", length = 10)
    public String getAddressCode() {
        return this.addressCode;
    }

    public void setAddressCode(String addressCode) {
        this.addressCode = addressCode;
    }

    @Column(name = "address_county", length = 20)
    public String getAddressCounty() {
        return this.addressCounty;
    }

    @Column(name = "address_sc")
    public String getAddressSc() {
        return addressSc;
    }

    public void setAddressSc(String addressSc) {
        this.addressSc = addressSc;
    }

    @Column(name = "address_apartment")
    public String getAddressApartment() {
        return addressApartment;
    }

    public void setAddressApartment(String addressApartment) {
        this.addressApartment = addressApartment;
    }

    public void setAddressCounty(String addressCounty) {
        this.addressCounty = addressCounty;
    }

    @Column(name = "address_country", nullable = false, length = 20)
    public String getAddressCountry() {
        return this.addressCountry;
    }

    public void setAddressCountry(String addressCountry) {
        this.addressCountry = addressCountry;
    }

    @Column(name = "telephone", nullable = false, length = 15)
    public String getTelephone() {
        return this.telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    @Column(name = "email", nullable = false, length = 50)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Column(name = "birth_date_day", nullable = false)
    public Byte getBirthDateDay() {
        return this.birthDateDay;
    }

    public void setBirthDateDay(Byte birthDateDay) {
        this.birthDateDay = birthDateDay;
    }

    @Column(name = "birth_date_month", nullable = false)
    public Byte getBirthDateMonth() {
        return this.birthDateMonth;
    }

    public void setBirthDateMonth(Byte birthDateMonth) {
        this.birthDateMonth = birthDateMonth;
    }

    @Column(name = "birth_date_year", nullable = false)
    public Short getBirthDateYear() {
        return this.birthDateYear;
    }

    public void setBirthDateYear(Short birthDateYear) {
        this.birthDateYear = birthDateYear;
    }

    @Column(name = "birth_place_city", nullable = false, length = 30)
    public String getBirthPlaceCity() {
        return this.birthPlaceCity;
    }

    public void setBirthPlaceCity(String birthPlaceCity) {
        this.birthPlaceCity = birthPlaceCity;
    }

    @Column(name = "birth_place_county", length = 20)
    public String getBirthPlaceCounty() {
        return this.birthPlaceCounty;
    }

    public void setBirthPlaceCounty(String birthPlaceCounty) {
        this.birthPlaceCounty = birthPlaceCounty;
    }

    @Column(name = "birth_place_country", length = 30)
    public String getBirthPlaceCountry() {
        return this.birthPlaceCountry;
    }

    public void setBirthPlaceCountry(String birthPlaceCountry) {
        this.birthPlaceCountry = birthPlaceCountry;
    }

    @Column(name = "temporary_membership", nullable = false)
    public boolean isTemporaryMembership() {
        return this.temporaryMembership;
    }

    public void setTemporaryMembership(boolean temporaryMembership) {
        this.temporaryMembership = temporaryMembership;
    }

    @Column(name = "license_number", length = 15)
    public String getLicenseNumber() {
        return this.licenseNumber;
    }

    public void setLicenseNumber(String licenseNumber) {
        this.licenseNumber = licenseNumber;
    }

    @Column(name = "b_license", nullable = false)
    public boolean isBLicense() {
        return this.BLicense;
    }

    public void setBLicense(boolean BLicense) {
        this.BLicense = BLicense;
    }

    @Column(name = "b_towing_winch", nullable = false)
    public boolean isBTowingWinch() {
        return this.BTowingWinch;
    }

    public void setBTowingWinch(boolean BTowingWinch) {
        this.BTowingWinch = BTowingWinch;
    }

    @Column(name = "b_towing_plane", nullable = false)
    public boolean isBTowingPlane() {
        return this.BTowingPlane;
    }

    public void setBTowingPlane(boolean BTowingPlane) {
        this.BTowingPlane = BTowingPlane;
    }

    @Column(name = "b_towing_self", nullable = false)
    public boolean isBTowingSelf() {
        return this.BTowingSelf;
    }

    public void setBTowingSelf(boolean BTowingSelf) {
        this.BTowingSelf = BTowingSelf;
    }

    @Column(name = "b_acrobatic_flight", nullable = false)
    public boolean isBAcrobaticFlight() {
        return this.BAcrobaticFlight;
    }

    public void setBAcrobaticFlight(boolean BAcrobaticFlight) {
        this.BAcrobaticFlight = BAcrobaticFlight;
    }

    @Column(name = "b_in_clouds_flight", nullable = false)
    public boolean isBInCloudsFlight() {
        return this.BInCloudsFlight;
    }

    public void setBInCloudsFlight(boolean BInCloudsFlight) {
        this.BInCloudsFlight = BInCloudsFlight;
    }

    @Column(name = "b_night_flight", nullable = false)
    public boolean isBNightFlight() {
        return this.BNightFlight;
    }

    public void setBNightFlight(boolean BNightFlight) {
        this.BNightFlight = BNightFlight;
    }

    @Column(name = "b_control_flight", nullable = false)
    public boolean isBControlFlight() {
        return this.BControlFlight;
    }

    public void setBControlFlight(boolean BControlFlight) {
        this.BControlFlight = BControlFlight;
    }

    @Column(name = "b_glider_license", nullable = false)
    public boolean isBGliderLicense() {
        return this.BGliderLicense;
    }

    public void setBGliderLicense(boolean BGliderLicense) {
        this.BGliderLicense = BGliderLicense;
    }

    @Column(name = "b_motorglider_license", nullable = false)
    public boolean isBMotorgliderLicense() {
        return this.BMotorgliderLicense;
    }

    public void setBMotorgliderLicense(boolean BMotorgliderLicense) {
        this.BMotorgliderLicense = BMotorgliderLicense;
    }

    @Column(name = "b_instructor", nullable = false)
    public boolean isBInstructor() {
        return this.BInstructor;
    }

    public void setBInstructor(boolean BInstructor) {
        this.BInstructor = BInstructor;
    }

    @Column(name = "b_test_pilot", nullable = false)
    public boolean isBTestPilot() {
        return this.BTestPilot;
    }

    public void setBTestPilot(boolean BTestPilot) {
        this.BTestPilot = BTestPilot;
    }

    @Column(name = "experience_nr_hours")
    public Integer getExperienceNrHours() {
        return this.experienceNrHours;
    }

    public void setExperienceNrHours(Integer experienceNrHours) {
        this.experienceNrHours = experienceNrHours;
    }

    @Column(name = "experience_nr_takeoffs")
    public Integer getExperienceNrTakeoffs() {
        return this.experienceNrTakeoffs;
    }

    public void setExperienceNrTakeoffs(Integer experienceNrTakeoffs) {
        this.experienceNrTakeoffs = experienceNrTakeoffs;
    }

    @Column(name = "experience_nr_km")
    public Integer getExperienceNrKm() {
        return this.experienceNrKm;
    }

    public void setExperienceNrKm(Integer experienceNrKm) {
        this.experienceNrKm = experienceNrKm;
    }

    @Column(name = "photo")
    public byte[] getPhoto() {
        return this.photo;
    }

    public void setPhoto(byte[] photo) {
        this.photo = photo;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "member_id")
    public Member getMember() {
        return member;
    }

    public void setMember(Member member) {
        this.member = member;
    }

    @Temporal(TemporalType.DATE)
    @Column(name = "add_date")
    public Date getAddDate() {
        return addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    @Transient
    public String getPhotoString() {
        if (photo != null) {
            return new BASE64Encoder().encode(photo);
        } else {
            return "";
        }
    }
}
